/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.aldrin.cafsysv2.gui.dialog.au;


import com.aldrin.cafsysv2.CafSysv2;
import com.aldrin.cafsysv2.dao.impl.CategoryDAOImpl;
import com.aldrin.cafsysv2.dao.impl.MenuDAOImpl;
import com.aldrin.cafsysv2.gui.JFrameCafSys;
import com.aldrin.cafsysv2.model.Category;
import com.aldrin.cafsysv2.model.Menu;
import com.aldrin.cafsysv2.util.ComboBoxList;
import com.formdev.flatlaf.FlatClientProperties;
import com.formdev.flatlaf.extras.FlatSVGIcon;
import java.awt.AlphaComposite;
import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.RenderingHints;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.net.URISyntaxException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author ALDRIN B. C.
 */
public class JDialogMenuAU extends javax.swing.JDialog {

    private CategoryDAOImpl categoryDAOImpl = new CategoryDAOImpl();
    private MenuDAOImpl menuDAOImpl = new MenuDAOImpl();
    private JFrameCafSys jFrameCafSys;

    /**
     * Creates new form JDialogMenuAU
     */
    private Menu menu = new Menu();
    static String title = "";

    public JDialogMenuAU(JFrameCafSys jFrameSariPOS, boolean modal) {
        super(jFrameSariPOS, modal);
        initComponents();
        this.jFrameCafSys =jFrameSariPOS;
        setTitle("NEW");
        this.title = "New";
        jTextFieldRecipe.putClientProperty(FlatClientProperties.PLACEHOLDER_TEXT, "RECIPE");
        jTextFieldPrice.putClientProperty(FlatClientProperties.PLACEHOLDER_TEXT, "PRICE");
        jTextAreaIngredients.putClientProperty(FlatClientProperties.PLACEHOLDER_TEXT, "INGREDIENTS");
        comboBoxCategory();
        jButton1.setIcon(new FlatSVGIcon("svg/save.svg",24,24));
        

    }

    public JDialogMenuAU(JFrameCafSys jFrameCafSys, boolean modal,Menu menu, String title) {
        super(jFrameCafSys, modal);
        initComponents();
        setTitle("UPDATE");
        this.menu = menu;
        this.title = title;
        jTextFieldRecipe.putClientProperty(FlatClientProperties.PLACEHOLDER_TEXT, "RECIPE");
        jTextFieldPrice.putClientProperty(FlatClientProperties.PLACEHOLDER_TEXT, "PRICE");
        jTextAreaIngredients.putClientProperty(FlatClientProperties.PLACEHOLDER_TEXT, "INGREDIENTS");
        comboBoxCategory();
        jTextFieldRecipe.setText(menu.getRecipe());
        jTextFieldPrice.setText(String.valueOf(menu.getPrice()));
        jTextAreaIngredients.setText(menu.getIngredients());
        for (ComboBoxList a : this.categoryDAOImpl.getList()) {
            a.setSelectedId(categoryDAOImpl.getList(), String.valueOf(menu.getCategory().getId()), jComboBoxCategory);
        }
        displayPicture(menu);
        jButton1.setIcon(new FlatSVGIcon("svg/edit.svg",24,24));

    }

    public JDialogMenuAU(JFrameCafSys jFrameCafSys, boolean modal, String title, Menu menu) {
        super(jFrameCafSys, modal);
        initComponents();
        setTitle("DELETE");
        this.menu = menu;
        this.title = title;
        jTextFieldRecipe.putClientProperty(FlatClientProperties.PLACEHOLDER_TEXT, "RECIPE");
        jTextFieldPrice.putClientProperty(FlatClientProperties.PLACEHOLDER_TEXT, "PRICE");
        jTextAreaIngredients.putClientProperty(FlatClientProperties.PLACEHOLDER_TEXT, "INGREDIENTS");
        comboBoxCategory();
        jTextFieldRecipe.setText(menu.getRecipe());
        jTextFieldPrice.setText(String.valueOf(menu.getPrice()));
        jTextAreaIngredients.setText(menu.getIngredients());
        for (ComboBoxList a : this.categoryDAOImpl.getList()) {
            a.setSelectedId(categoryDAOImpl.getList(), String.valueOf(menu.getCategory().getId()), jComboBoxCategory);
        }
        displayPicture(menu);
        jButton1.setIcon(new FlatSVGIcon("svg/delete.svg",24,24));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooser1 = new javax.swing.JFileChooser();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldRecipe = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldPrice = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabelPicture = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jComboBoxCategory = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaIngredients = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("MENU");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("RECIPE:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 20, 80, 30));

        jTextFieldRecipe.setPreferredSize(new java.awt.Dimension(64, 30));
        getContentPane().add(jTextFieldRecipe, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, 340, -1));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 220, 80, 30));

        jTextFieldPrice.setPreferredSize(new java.awt.Dimension(64, 30));
        getContentPane().add(jTextFieldPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, 340, -1));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)), "PHOTO", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(0, 102, 153))); // NOI18N
        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        jPanel2.setLayout(new java.awt.BorderLayout());

        jLabelPicture.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelPicture.setText("No Photo");
        jLabelPicture.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelPictureMouseClicked(evt);
            }
        });
        jPanel2.add(jLabelPicture, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel2, java.awt.BorderLayout.CENTER);

        jPanel3.setPreferredSize(new java.awt.Dimension(210, 0));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel3, java.awt.BorderLayout.NORTH);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 10, 210, 220));

        jButton1.setText("Save");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 280, 168, 32));

        jComboBoxCategory.setPreferredSize(new java.awt.Dimension(72, 32));
        getContentPane().add(jComboBoxCategory, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 100, 340, 30));

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("PRICE:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 60, 80, 30));

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel10.setText("CATEGORY:");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 100, 80, 30));

        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel11.setText("INGREDIENTS:");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 140, 80, 30));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        jPanel4.setPreferredSize(new java.awt.Dimension(100, 1));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 638, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 251, 640, -1));

        jTextAreaIngredients.setColumns(20);
        jTextAreaIngredients.setRows(5);
        jScrollPane1.setViewportView(jTextAreaIngredients);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 140, 340, -1));

        setSize(new java.awt.Dimension(675, 376));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (this.title.equals("New")) {
            int response = JOptionPane.showConfirmDialog(jFrameCafSys, "Are you sure to save " + jTextFieldRecipe.getText() + " " + jTextFieldPrice.getText() + " ?", "Save confirmation", JOptionPane.YES_NO_OPTION);
            if (response == JOptionPane.YES_OPTION) {
                this.menu.setRecipe(jTextFieldRecipe.getText());
                this.menu.setPrice(Float.parseFloat(jTextFieldPrice.getText()));
                this.menu.setIngredients(jTextAreaIngredients.getText());
                ComboBoxList categoryId = (ComboBoxList) this.jComboBoxCategory.getSelectedItem();
                Category category = new Category();
                category.setId(categoryId.getId());
                this.menu.setCategory(category);
                try {
                    validatePhoto();
                } catch (URISyntaxException ex) {
                    Logger.getLogger(JDialogMenuAU.class.getName()).log(Level.SEVERE, null, ex);
                }
                menuDAOImpl.addMenu(menu);
                this.dispose();
            }
        } else if (this.title.equals("Update")) {
            int response = JOptionPane.showConfirmDialog(jFrameCafSys, "Are you sure to update " + jTextFieldRecipe.getText() + " " + jTextFieldPrice.getText() + " ?", "Save confirmation", JOptionPane.YES_NO_OPTION);
            if (response == JOptionPane.YES_OPTION) {
                this.menu.setRecipe(jTextFieldRecipe.getText());
                this.menu.setPrice(Float.parseFloat(jTextFieldPrice.getText()));
                this.menu.setIngredients(jTextAreaIngredients.getText());
                ComboBoxList categoryId = (ComboBoxList) this.jComboBoxCategory.getSelectedItem();
                Category category = new Category();
                category.setId(categoryId.getId());
                this.menu.setCategory(category);
                try {
                    validatePhoto();
                } catch (URISyntaxException ex) {
                    Logger.getLogger(JDialogMenuAU.class.getName()).log(Level.SEVERE, null, ex);
                }
                menuDAOImpl.updateMenu(menu);
                this.dispose();
            }
        } else if (this.title.equals("Delete")) {
            int response = JOptionPane.showConfirmDialog(jFrameCafSys, "Are you sure to delete " + jTextFieldRecipe.getText() + " " + jTextFieldPrice.getText() + " ?", "Save confirmation", JOptionPane.YES_NO_OPTION);
            if (response == JOptionPane.YES_OPTION) {
                menuDAOImpl.deleteMenu(menu);
                this.dispose();
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jLabelPictureMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelPictureMouseClicked

        browse();
    }//GEN-LAST:event_jLabelPictureMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<Object> jComboBoxCategory;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelPicture;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextAreaIngredients;
    private javax.swing.JTextField jTextFieldPrice;
    private javax.swing.JTextField jTextFieldRecipe;
    // End of variables declaration//GEN-END:variables

    private void comboBoxCategory() {
        categoryDAOImpl.comboBoxCategory();
        jComboBoxCategory.removeAllItems();
        for (ComboBoxList a : categoryDAOImpl.getList()) {
            this.jComboBoxCategory.addItem(a);
        }
    }

    private File pictureFile = null;

    private void browse() {
        try {
            int returnVal = jFileChooser1.showOpenDialog(this);
            if (returnVal == javax.swing.JFileChooser.APPROVE_OPTION) {
                pictureFile = jFileChooser1.getSelectedFile();
                uploadPhoto(pictureFile);
                int IMG_WIDTH = jLabelPicture.getWidth();
                int IMG_HEIGHT = jLabelPicture.getHeight();
                if(pictureFile!=null){
                    jLabelPicture.setText("");
                }

                try {
                    BufferedImage originalImage = ImageIO.read(pictureFile);
                    int type = originalImage.getType() == 0 ? BufferedImage.TYPE_INT_ARGB : originalImage.getType();

                    BufferedImage resizedImage = new BufferedImage(IMG_WIDTH, IMG_HEIGHT, type);
                    Graphics2D g = resizedImage.createGraphics();
                    g.drawImage(originalImage, 0, 0, IMG_WIDTH, IMG_HEIGHT, null);
                    g.dispose();
                    g.setComposite(AlphaComposite.Src);

                    g.setRenderingHint(RenderingHints.KEY_INTERPOLATION,
                            RenderingHints.VALUE_INTERPOLATION_BILINEAR);
                    g.setRenderingHint(RenderingHints.KEY_RENDERING,
                            RenderingHints.VALUE_RENDER_QUALITY);
                    g.setRenderingHint(RenderingHints.KEY_ANTIALIASING,
                            RenderingHints.VALUE_ANTIALIAS_ON);

                    jLabelPicture.setIcon(new ImageIcon(resizedImage)); //to eliminate .jpeg from picture filename
                    ImageIO.write(resizedImage, "png", new File(CafSysv2.class.getProtectionDomain().getCodeSource().getLocation().getPath() + "\\images\\model.jpg"));

                } catch (final IOException ex) {
                    
                }

            } else {
                File defaultDirectory = new File(System.getProperty("user.home"));
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void uploadPhoto(File file) {
        if (file != null) {
            try (FileInputStream fis = new FileInputStream(file)) {
                byte[] imageData = new byte[(int) file.length()];
                fis.read(imageData);
                menu.setPhoto(imageData);
            } catch (IOException e) {
                e.printStackTrace();
            }
        }
    }
    int IMG_WIDTH = 200;
    int IMG_HEIGHT = 200;

    private void displayPicture(Menu menu) {
        try {
            byte[] imageData = menu.getPhoto();
            ImageIcon imageIcon = new ImageIcon(imageData);

            Image image = imageIcon.getImage();
            int type = BufferedImage.TYPE_INT_ARGB;

            BufferedImage resizedImage = new BufferedImage(IMG_WIDTH, IMG_HEIGHT, type);
            Graphics2D g = resizedImage.createGraphics();
            g.drawImage(image, 0, 0, IMG_WIDTH, IMG_HEIGHT, null);
            g.dispose();
            g.setComposite(AlphaComposite.Src);

            g.setRenderingHint(RenderingHints.KEY_INTERPOLATION,
                    RenderingHints.VALUE_INTERPOLATION_BILINEAR);
            g.setRenderingHint(RenderingHints.KEY_RENDERING,
                    RenderingHints.VALUE_RENDER_QUALITY);
            g.setRenderingHint(RenderingHints.KEY_ANTIALIASING,
                    RenderingHints.VALUE_ANTIALIAS_ON);

            jLabelPicture.setIcon(new ImageIcon(resizedImage));//image to label

        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void validatePhoto() throws URISyntaxException {
        if (menu.getPhoto() == null) {
            File targetClassesDir = new File(CafSysv2.class.getProtectionDomain().getCodeSource().getLocation().getPath() + "\\images\\no photo.jpg");
            try {
                FileInputStream fis = new FileInputStream(targetClassesDir);
                byte[] imageData = new byte[(int) targetClassesDir.length()];
                fis.read(imageData);
                menu.setPhoto(imageData);
            } catch (Exception e) {
                System.out.println("default of no photo is error");
            }
        }
    }

}
